{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: error test \nassert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test.test_demo.TestClass object at 0x1019d5b50>\n\n    @pytest.mark.slow\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\"),\"error test \"\nE       AssertionError: error test \nE       assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest/test_demo.py:12: AssertionError"}, "start": 1715229518496, "stop": 1715229518496, "uuid": "5c16cb00-a826-4326-a811-f9768e4a2008", "historyId": "9058e07b435905553cc481319998fc23", "testCaseId": "f5786294eb840dda5976ff0a55a4581a", "fullName": "test.test_demo.TestClass#test_two", "labels": [{"name": "tag", "value": "slow"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "deipssdeMacBook-Air.local"}, {"name": "thread", "value": "20764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_demo"}]}